/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.myproject;

import com.myproject.designpatterns.singleton.Singleton;

public class App {
    private static void singletonExample() {
        Singleton singleton = Singleton.getInstance();
        Singleton singleton1 = Singleton.getInstance();

        //returning same instance of object each time.
        System.out.println(singleton);
        System.out.println(singleton1);
    }

    public static void main(String[] args) {
        System.out.println("Design Patterns..");

        System.out.println("- Singleton");
        singletonExample();
    }
}
